---
- name: Install telegraf 
  hosts: lab
  become: true
  roles:
  - { role: telegraf, tags: ["telegraf"] }

- name: install libvirt
  hosts: ops-com
  become: true
  roles:
  - { role: libvirt_exporter, tags: ["libvirt_exporter"] }

- name: install ceph_exporter
  hosts: cephadmin
  become: true
  roles:
  - { role: ceph_exporter, tags: ["ceph_exporter"] }

- name: install filebeat
  hosts: lab
  become: true
  roles:
  - { role: filebeat, tags: ["filebeat"] }