
- name: Creates directory kibana
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: 1000
    group: 1000
  with_items:
  - "{{ kibana_conf_dir }}/config"
  - "{{ kibana_conf_dir }}/data"
  - "{{ kibana_conf_dir }}/plugins"


- name: Coppy file kibana.yml
  template:
    src: "templates/kibana.yml.j2"
    dest: "{{ kibana_conf_dir }}/config/kibana.yml"
- name: Start kibana container
  docker_container:
    name: "{{ kibana_hostname }}"
    image: docker.elastic.co/kibana/kibana:{{ ELK_VERSION }}
    state: started
    restart: yes
    restart_policy: always
    volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    - "{{ kibana_conf_dir }}/config/kibana.yml:{{ kibana_conf_dir }}/config/kibana.yml:rw"
    - "{{ kibana_conf_dir }}/data:{{ kibana_conf_dir }}/data:rw"
    - "{{ kibana_conf_dir }}/plugins:{{ kibana_conf_dir }}/plugins:rw"
    - "{{ elasticsearch_conf_dir }}/certs:{{ kibana_conf_dir }}/config/certs:ro"
    env:
      ELASTICSEARCH_USERNAME: "{{ elastic_user }}"
      ELASTICSEARCH_PASSWORD: "{{ elastic_password }}"
    network_mode: host
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_max_size }}"
      max-file: "{{ log_max_file }}"

- name: Allow port kibana
  ufw:
    rule: allow
    port: '{{ kibana_PORT }}'