---
- name: Create container docker telegram bot
  docker_container:
    name: telegram-bot
    image: hungnv1008/alertmanager-webhook-telegram
    pull: yes
    state: started
    restart: yes
    restart_policy: always
    network_mode: host
    volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    - "{{ Prometheus_conf_local }}:{{ Prometheus_conf_container }}:ro"
    - "{{ Prometheus_conf_local }}:{{ Prometheus_conf_container }}/data:rw"
    - "{{ alertmanager_conf_local }}:{{ alertmanager_conf_local }}:ro"
    - "{{ alertmanager_conf_local }}/alertmanager.yml:{{ alertmanager_conf_container }}/alertmanager.yml:rw"
    - "{{ alertmanager_conf_local }}/notifications.tmpl:{{ alertmanager_conf_container }}/notifications.tmpl:rw"
    env:
      bottoken: "6247246657:AAEBWRe43CARN7BXNHMWgxBJtbnm_HS6Y8M"
      chatid: "-1001805644970"
      username: "{{ alert_username }}"
      password: "{{ alert_password }}"
