---
- include_tasks: "telegraf-server-basic.yml"
  when:
    - inventory_hostname in groups["all"]

- include_tasks: "telegraf-ops-controller.yml"
  when: inventory_hostname in groups["controller"]

- include_tasks: "telegraf-ceph.yml"
  when: inventory_hostname in groups["ceph"]